export const BOT_LINK = 'https://t.me/your_bot';

export const content = {
  en: {
    nav: ['Features', 'Pricing', 'How it works', 'Referral', 'FAQ'],
    eyebrow: 'Faster. Stable. Secure.',
    heroTitleA: 'Speed Up Your',
    heroTitleB: 'Internet.',
    heroTitleC: 'Instantly.',
    heroText: 'Our service makes your connection faster, more stable and more reliable for everything you do online.',
    start: 'Start 3-Day Free Trial',
    how: 'How it works',
    badges: ['3-Day Free Trial', 'Cancel Anytime', 'No Hidden Fees'],
    features: [
      ['🛡', 'Blazing Fast', 'Optimized routing for maximum speed'],
      ['ϟ', 'Stable Connection', 'No more ping spikes or random drops'],
      ['◎', 'Global Network', 'Servers in multiple countries'],
      ['🔒', 'Secure & Private', 'Your data is encrypted and protected'],
    ],
    choose: 'Choose Your Plan',
    sub: 'All plans include 3-day free trial',
    plans: [
      ['Social Boost', 'Perfect for social media and browsing', '$3', ['Faster social apps', 'Stable connection', 'Worldwide servers', '3-Day Free Trial']],
      ['Gaming', 'Low ping. Zero lag. Game on.', '$4', ['Optimized for games', 'Ultra-low ping', 'Stable connection', '3-Day Free Trial']],
      ['Full Access', 'Everything. Everywhere. No limits.', '$5', ['All features included', 'Global network', 'Priority support', '3-Day Free Trial']],
    ],
    popular: 'MOST POPULAR',
    startTrial: 'Start Trial',
    howTitle: 'How It Works',
    steps: [
      ['✈', 'Start in Telegram', 'Click the button and open our bot'],
      ['ϟ', 'Choose Your Plan', 'Pick a plan that fits your needs'],
      ['✓', 'Activate & Enjoy', 'Start your trial and enjoy faster internet'],
    ],
    referralTitleA: 'Invite 3 Friends',
    referralTitleB: 'Get 7 Days Free',
    referralText: 'Share your link with friends. When 3 friends join — you get 7 days free on any plan.',
    learn: 'Learn More in Bot',
    faqTitle: 'Frequently Asked Questions',
    faq: [
      ['Is there a free trial?', 'Yes, 3 days free.'],
      ['Can I cancel anytime?', 'Yes, anytime.'],
      ['What payment methods do you accept?', 'Payments are handled in Telegram bot.'],
      ['Will this work for gaming?', 'Choose Gaming plan for the best experience.'],
      ['Is my data safe?', 'The service uses protected encrypted access.'],
    ],
    finalA: 'Ready to Speed Up',
    finalB: 'Your Internet?',
    finalBtn: 'Start Your 3-Day Trial',
    cancel: 'Cancel Anytime',
  },
  ru: {
    nav: ['Плюсы', 'Тарифы', 'Как работает', 'Бонус', 'FAQ'],
    eyebrow: 'Быстрее. Стабильнее. Безопаснее.',
    heroTitleA: 'Ускорьте свой',
    heroTitleB: 'интернет.',
    heroTitleC: 'Мгновенно.',
    heroText: 'Сервис помогает сделать соединение быстрее, стабильнее и удобнее для ежедневного использования.',
    start: 'Запустить 3 дня бесплатно',
    how: 'Как это работает',
    badges: ['3 дня бесплатно', 'Отмена в любой момент', 'Без скрытых платежей'],
    features: [
      ['🛡', 'Очень быстро', 'Оптимизированный маршрут для скорости'],
      ['ϟ', 'Стабильное соединение', 'Меньше скачков пинга и обрывов'],
      ['◎', 'Глобальная сеть', 'Серверы в разных странах'],
      ['🔒', 'Безопасно', 'Данные защищены и зашифрованы'],
    ],
    choose: 'Выберите тариф',
    sub: 'Во всех тарифах есть 3 дня бесплатно',
    plans: [
      ['Social Boost', 'Для соцсетей и браузинга', '$3', ['Быстрее соцсети', 'Стабильное соединение', 'Серверы по миру', '3 дня бесплатно']],
      ['Gaming', 'Низкий пинг. Меньше лагов.', '$4', ['Оптимизация для игр', 'Низкий пинг', 'Стабильное соединение', '3 дня бесплатно']],
      ['Full Access', 'Всё включено. Без лимитов.', '$5', ['Все функции', 'Глобальная сеть', 'Приоритетная поддержка', '3 дня бесплатно']],
    ],
    popular: 'ПОПУЛЯРНЫЙ',
    startTrial: 'Начать триал',
    howTitle: 'Как это работает',
    steps: [
      ['✈', 'Запуск в Telegram', 'Нажмите кнопку и откройте бота'],
      ['ϟ', 'Выберите тариф', 'Подберите нужный тариф'],
      ['✓', 'Активируйте доступ', 'Запустите триал и пользуйтесь'],
    ],
    referralTitleA: 'Пригласите 3 друзей',
    referralTitleB: 'Получите 7 дней бесплатно',
    referralText: 'Поделитесь ссылкой. Когда 3 друга подключатся — получите 7 дней бесплатно.',
    learn: 'Подробнее в боте',
    faqTitle: 'Частые вопросы',
    faq: [
      ['Есть бесплатный триал?', 'Да, 3 дня бесплатно.'],
      ['Можно отменить в любой момент?', 'Да, в любой момент.'],
      ['Как проходит оплата?', 'Оплата проходит через Telegram-бот.'],
      ['Подойдёт для игр?', 'Для игр лучше выбрать тариф Gaming.'],
      ['Данные защищены?', 'Сервис использует защищённый доступ.'],
    ],
    finalA: 'Готовы ускорить',
    finalB: 'интернет?',
    finalBtn: 'Запустить триал',
    cancel: 'Отмена в любой момент',
  },
};
