export const BOT_LINK = 'https://t.me/your_bot';

export const t = {
  en: {
    nav: ['Features', 'Pricing', 'How it works', 'Referral', 'FAQ'],
    heroTitle: <>Speed Up Your <span className="red">Internet.</span> Instantly.</>,
    eyebrow: 'Faster. Stable. Secure.',
    heroText: 'Our service makes your connection faster, more stable and more reliable for everything you do online.',
    start: 'Start 3-Day Free Trial',
    how: 'How it works',
    badges: ['3-Day Free Trial', 'Cancel Anytime', 'No Hidden Fees'],
    featuresTitle: ['Blazing Fast', 'Stable Connection', 'Global Network', 'Secure & Private'],
    featuresText: ['Optimized routing for maximum speed', 'No more ping spikes or random drops', 'Servers in multiple countries', 'Your data is encrypted and protected'],
    choose: 'Choose Your Plan',
    sub: 'All plans include 3-day free trial',
    plans: [
      ['Social Boost', 'Perfect for social media and browsing', '$3', ['Faster social apps', 'Stable connection', 'Worldwide servers', '3-Day Free Trial']],
      ['Gaming', 'Low ping. Zero lag. Game on.', '$4', ['Optimized for games', 'Ultra-low ping', 'Stable connection', '3-Day Free Trial']],
      ['Full Access', 'Everything. Everywhere. No limits.', '$5', ['All features included', 'Global network', 'Priority support', '3-Day Free Trial']],
    ],
    popular: 'MOST POPULAR',
    startTrial: 'Start Trial',
    howTitle: 'How It Works',
    steps: [['Start in Telegram', 'Click the button and open our bot'], ['Choose Your Plan', 'Pick a plan that fits your needs'], ['Activate & Enjoy', 'Start your trial and enjoy faster internet']],
    referralTitle: <>Invite 3 Friends<br />Get 7 Days Free</>,
    referralText: 'Share your link with friends. When 3 friends join — you get 7 days free on any plan.',
    learn: 'Learn More in Bot',
    final: <>Ready to Speed Up<br />Your Internet?</>,
  },
  ru: {
    nav: ['Плюсы', 'Тарифы', 'Как работает', 'Бонус', 'FAQ'],
    heroTitle: <>Ускорьте свой <span className="red">интернет.</span> Мгновенно.</>,
    eyebrow: 'Быстрее. Стабильнее. Безопаснее.',
    heroText: 'Сервис помогает сделать соединение быстрее, стабильнее и удобнее для ежедневного использования.',
    start: 'Запустить 3 дня бесплатно',
    how: 'Как это работает',
    badges: ['3 дня бесплатно', 'Отмена в любой момент', 'Без скрытых платежей'],
    featuresTitle: ['Очень быстро', 'Стабильное соединение', 'Глобальная сеть', 'Безопасно'],
    featuresText: ['Оптимизированный маршрут для скорости', 'Меньше скачков пинга и обрывов', 'Серверы в разных странах', 'Данные защищены и зашифрованы'],
    choose: 'Выберите тариф',
    sub: 'Во всех тарифах есть 3 дня бесплатно',
    plans: [
      ['Social Boost', 'Для соцсетей и браузинга', '$3', ['Быстрее соцсети', 'Стабильное соединение', 'Серверы по миру', '3 дня бесплатно']],
      ['Gaming', 'Низкий пинг. Меньше лагов.', '$4', ['Оптимизация для игр', 'Низкий пинг', 'Стабильное соединение', '3 дня бесплатно']],
      ['Full Access', 'Всё включено. Без лимитов.', '$5', ['Все функции', 'Глобальная сеть', 'Приоритетная поддержка', '3 дня бесплатно']],
    ],
    popular: 'ПОПУЛЯРНЫЙ',
    startTrial: 'Начать триал',
    howTitle: 'Как это работает',
    steps: [['Запуск в Telegram', 'Нажмите кнопку и откройте бота'], ['Выберите тариф', 'Подберите нужный тариф'], ['Активируйте доступ', 'Запустите триал и пользуйтесь']],
    referralTitle: <>Пригласите 3 друзей<br />Получите 7 дней бесплатно</>,
    referralText: 'Поделитесь ссылкой. Когда 3 друга подключатся — получите 7 дней бесплатно.',
    learn: 'Подробнее в боте',
    final: <>Готовы ускорить<br />интернет?</>,
  },
};
